from tkinter import *

from DatabasePython import cur, con

root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
home=PhotoImage(file='home.png')
bus=PhotoImage(file='.\\Bus_for_project.png')
fr1=Frame(root)
fr1.grid(row=0,column=0,columnspan=10)
fr2=Frame(root)
fr2.grid(row=1,column=0,columnspan=10)
fr3=Frame(root)
fr3.grid(row=3,column=0,columnspan=10)
fr4=Frame(root)
fr4.grid(row=4,column=0,columnspan=10)
Label(fr1,image=bus).grid(row=0,column=1,padx=w//2.5)
Label(fr2,text='Online Bus Booking System',fg='red',bg='light Blue',font='arial 30 bold').grid(row=1,column=1,pady=w//40)
Label(fr2,text='Add Bus Running Details',fg='green',font='arial 20 bold').grid(row=2,column=1,pady=w//40)
Label(fr3,text='Bus ID',font='arial 20 bold').grid(row=3,column=2,padx=5)
y=Entry(fr3)
y.grid(row=3,column=3,padx=5)
Label(fr3,text='Running Date',font='arial 20 bold').grid(row=3,column=4,padx=5)
z=Entry(fr3)
z.grid(row=3,column=5,padx=5)
Label(fr3,text='Seat Available',font='arial 20 bold').grid(row=3,column=6,padx=5)
a=Entry(fr3)
a.grid(row=3,column=7,padx=5)
def home4():
    root.destroy()
    import AddNewDetailToDataBase
def runningdetail():
    Label(fr4, text=int(y.get())).grid(row=4, column=5)
    Label(fr4, text=z.get()).grid(row=4, column=6)
    Label(fr4, text=int(a.get())).grid(row=4, column=7)
    busid = y.get()
    runningdate = z.get()
    seatavailable= a.get()
    cur.execute('insert into Run(Bus_Id,Date,Seat_Available) values(?,?,?)', (busid,runningdate,seatavailable))
    con.commit()
Button(fr3,text='Add Run',font='arial 15 bold',bg='light green',command=runningdetail).grid(row=3,column=8,padx=40)
Button(fr3,text='Delete Run',font='arial 15 bold',bg='light green').grid(row=3,column=9,padx=40)
Button(fr4,image=home,command=home4).grid(row=5,column=7,pady=100)
root.mainloop()