from tkinter import *

from DatabasePython import cur, con

root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
home=PhotoImage(file='home.png')
bus=PhotoImage(file='.\\Bus_for_project.png')
home=PhotoImage(file='home.png')
fr1=Frame(root)
fr1.grid(row=0,column=0,columnspan=10)
fr2=Frame(root)
fr2.grid(row=1,column=0,columnspan=10)
fr3=Frame(root)
fr3.grid(row=2,column=0,columnspan=10)
fr4=Frame(root)
fr4.grid(row=4,column=0,columnspan=10)
fr5=Frame(root)
fr5.grid(row=6,column=0,columnspan=10)
Label(fr1,image=bus).grid(row=0,column=1,padx=w//2.5)
Label(fr2,text='Online Bus Booking System',fg='red',bg='light Blue',font='arial 30 bold').grid(row=1,column=1,pady=w//40)
Label(fr2,text='Add Bus Operator Details',fg='green',font='arial 20 bold').grid(row=2,column=1,pady=w//40)
Label(fr3,text='Bus ID',font='arial 20 bold').grid(row=3,column=0,padx=5)
x=Entry(fr3)
x.grid(row=3,column=1,padx=5)
Label(fr3,text='Bus Type',font='arial 20 bold').grid(row=3,column=2,padx=5)
Bus_type=StringVar()
option=['AC 2X2','AC 3X2']
Bus_type.set('Select Bus')
menu=OptionMenu(fr3,Bus_type,*option)
menu.grid(row=3,column=3,padx=5)
Label(fr3,text='Capacity',font='arial 20 bold').grid(row=3,column=4,padx=5)
z=Entry(fr3)
z.grid(row=3,column=5,padx=5)
Label(fr3,text='Fare',font='arial 20 bold').grid(row=3,column=6,padx=5)
a=Entry(fr3)
a.grid(row=3,column=7,padx=5)
Label(fr3,text='Operator ID',font='arial 20 bold').grid(row=3,column=8,padx=5)
b=Entry(fr3)
b.grid(row=3,column=9,padx=5)
Label(fr3,text='Route ID',font='arial 20 bold').grid(row=3,column=10,padx=5)
c=Entry(fr3)
c.grid(row=3,column=11,padx=5)
def addbusdetail():
    Label(fr4,text=int(x.get())).grid(row=4,column=4)
    Label(fr4,text=Bus_type.get()).grid(row=4,column=5)
    Label(fr4,text=int(z.get())).grid(row=4,column=6)
    Label(fr4,text=int(a.get())).grid(row=4,column=7)
    Label(fr4,text=int(b.get())).grid(row=4,column=8)
    Label(fr4,text=int(c.get())).grid(row=4,column=9)
    bus = x.get()
    type = Bus_type.get()
    capacity = z.get()
    fare = a.get()
    operatorid = b.get()
    route = c.get()
    cur.execute('insert into Bus(Bus_ID,Type,Capacity,Fare,Op_ID,Route_Id) values(?,?,?,?,?,?)',(bus, type, capacity, fare, operatorid, route))
    con.commit()
def home1():
    root.destroy()
    import AddNewDetailToDataBase
Button(fr5,text='Add Bus',font='arial 15 bold',bg='Light green',command=addbusdetail).grid(row=7,column=4,pady=50,padx=20)
Button(fr5,text='Edit Bus',font='arial 15 bold',bg='Light green').grid(row=7,column=5,pady=50)
Button(fr5,image=home,command=home1).grid(row=6,column=6,padx=50)
root.mainloop()