from tkinter import *

from DatabasePython import cur, con

root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
home=PhotoImage(file='home.png')
bus=PhotoImage(file='.\\Bus_for_project.png')
fr1=Frame(root)
fr1.grid(row=0,column=0,columnspan=10)
fr2=Frame(root)
fr2.grid(row=1,column=0,columnspan=10)
fr3=Frame(root)
fr3.grid(row=2,column=0,columnspan=10)
fr4=Frame(root)
fr4.grid(row=4,column=0,columnspan=10)
fr5=Frame(root)
fr5.grid(row=5,column=0,columnspan=10)
Label(fr1,image=bus).grid(row=0,column=1,padx=w//2.5)
Label(fr2,text='Online Bus Booking System',fg='red',bg='light Blue',font='arial 30 bold').grid(row=1,column=1,pady=w//40)
Label(fr2,text='Add Bus Operator Details',fg='green',font='arial 20 bold').grid(row=2,column=1,pady=w//40)
Label(fr3,text='Route ID',font='arial 20 bold').grid(row=3,column=0,padx=5)
x=Entry(fr3)
x.grid(row=3,column=1,padx=5)
Label(fr3,text='Station Name',font='arial 20 bold').grid(row=3,column=2,padx=5)
y=Entry(fr3)
y.grid(row=3,column=3,padx=5)
Label(fr3,text='Station Id',font='arial 20 bold').grid(row=3,column=4,padx=5)
z=Entry(fr3)
z.grid(row=3,column=5,padx=5)
def addroute():
    Label(fr4, text=int(x.get())).grid(row=4, column=5, pady=10)
    Label(fr4, text=str(y.get())).grid(row=4, column=6, pady=10)
    Label(fr4, text=int(z.get())).grid(row=4, column=7, pady=10)
    routeid = x.get()
    sname = y.get()
    sid = z.get()
    cur.execute('insert into Route(Route_Id,SName,SID) values(?,?,?)',(routeid,sname,sid))
    con.commit()
def home3():
    root.destroy()
    import AddNewDetailToDataBase
Button(fr3,text='Add Route',bg='light green',font='arial 15 bold',command=addroute).grid(row=3,column=6,padx=50)
Button(fr3,text='Delete Route',bg='light green',fg='red',font='arial 15 bold').grid(row=3,column=7,padx=50)
Button(fr5,image=home,command=home3).grid(row=5,column=5,pady=20)
root.mainloop()