from tkinter import *
from tkinter.messagebox import *
from DatabasePython import cur, con
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
home=PhotoImage(file='home.png')
bus=PhotoImage(file='.\\Bus_for_project.png')
fr1=Frame(root)
fr1.grid(row=0,column=0,columnspan=10)
fr2=Frame(root)
fr2.grid(row=1,column=0,columnspan=10)
fr3=Frame(root)
fr3.grid(row=2,column=0,columnspan=10)
fr4=Frame(root)
fr4.grid(row=4,column=0,columnspan=10)
fr5=Frame(root)
fr5.grid(row=7,column=0,columnspan=10)
fr6=Frame(root)
fr6.grid(row=6,column=0,columnspan=10)
Label(fr1,image=bus).grid(row=0,column=1,padx=w//2.5)
Label(fr2,text='Online Bus Booking System',fg='red',bg='light Blue',font='arial 30 bold').grid(row=1,column=1,pady=w//40)
Label(fr2,text='Enter Journey Details',fg='green',bg='light green',font='arial 20 bold').grid(row=2,column=1,pady=w//40)
Label(fr3,text='To',font='arial 20 bold').grid(row=3,column=0,padx=5)
x=Entry(fr3,width=33)
x.grid(row=3,column=1,padx=5)
Label(fr3,text='From',font='arial 20 bold').grid(row=3,column=2,padx=5)
y=Entry(fr3,width=33)
y.grid(row=3,column=3,padx=5)
Label(fr3,text='Journey Date',font='arial 20 bold').grid(row=3,column=4,padx=5)
z=Entry(fr3,width=33)
z.grid(row=3,column=5,padx=5)
def home1():
    root.destroy()
    import SeatBokingorCheckBookedSeat
def Showbus():
    Label(fr4,text='Select Bus',font='arial 20 bold',fg='Green').grid(row=4,column=0,padx=20)
    Label(fr4,text='Operator',font='arial 20 bold',fg='Green').grid(row=4,column=1,padx=20)
    Label(fr4,text='Bus Type',font='arial 20 bold',fg='Green').grid(row=4,column=2,padx=20)
    Label(fr4,text='Available/Capacity',font='arial 20 bold',fg='Green').grid(row=4,column=3,padx=20)
    Label(fr4,text='Fare',font='arial 20 bold',fg='Green').grid(row=4,column=4,padx=20)
    Button(fr4,text='Proceed To Book',font='arial 15 bold',bg='light green',command=proceedtobook).grid(row=5,column=5)
    toplace=x.get()
    fromplace=y.get()
    cur.execute('select Bus_id,Op_id,Type,Capicity,Fare,')

Button(fr3, text='Show Bus', font='arial 15 bold', bg='green',command=Showbus).grid(row=3, column=6, padx=5)
Button(fr3, image=home,command=home1).grid(row=3, column=7)
def choice():
    ch = askyesno('Book Seat', 'Total Amount to be Paid')
    root.destroy()
    import BusTicket

def proceedtobook():
    Label(fr6, text='Fill Passenger Details To Book The Bus Ticket', fg='red', bg='light Blue', font='arial 30 bold').grid(row=6,column=5,pady=50)
    Label(fr5,text='Name',font='arial 20 bold').grid(row=7,column=0,padx=5)
    l=Entry(fr5,width=20)
    l.grid(row=7,column=1,padx=5)
    Label(fr5,text='Gender',font='arial 20 bold').grid(row=7,column=2,padx=5)
    option=['Male','Female','Other','Prefer not to say']
    gender=StringVar()
    gender.set("Male")
    menu=OptionMenu(fr5,gender,*option)
    menu.grid(row=7,column=3,padx=5)
    Label(fr5,text='No Of Seats',font='arial 20 bold').grid(row=7,column=4,padx=5)
    n=Entry(fr5,width=5)
    n.grid(row=7,column=5,padx=5)
    Label(fr5,text='Mobile No',font='arial 20 bold').grid(row=7,column=6,padx=5)
    o=Entry(fr5,width=20)
    o.grid(row=7,column=7,padx=5)
    Label(fr5,text='Age',font='arial 20 bold').grid(row=7,column=8,padx=5)
    p=Entry(fr5,width=5)
    p.grid(row=7,column=9,padx=5)
    Button(fr5,text='Book Seat',font='arial 10 bold',bg='light green',command=choice).grid(row=7,column=10,padx=5)
root.mainloop()
